#!/sbin/openrc-run
# author: detuur - no rights reserved

## Do not edit this file!
## User-settable variables are in /etc/conf.d/qbittorrent-nox

name=$RC_SVCNAME
description="qbittorrent daemon w/o ui"
command="/usr/bin/qbittorrent-nox"
command_background=true
pidfile="/var/run/${RC_SVCNAME}.pid"
output_log=${QBT_OUTLOG:-"/var/log/qbittorrent-nox/out"}
error_log=${QBT_ERRLOG:-"/var/log/qbittorrent-nox/err"}

# Only set command_user if QBT_USER is non-empty
if [ -n "$QBT_USER" ]; then
    command_user=$QBT_USER;
fi

command_args="\
 ${QBT_WEBUI_PORT:+--webui-port=}$QBT_WEBUI_PORT\
 ${QBT_PROFILE_DIR:+--profile=}$QBT_PROFILE_DIR\
 ${QBT_CONF_DIR:+--configuration=}$QBT_CONF_DIR\
"

depend() {
	need net
}
